### ISSUE TITLE
Feature: add a list of specific blocklists as part of installation

### ISSUE THREAD

**Issue by raoul361** [jsamuel1/pi-hole-cdk#1]
Insert into gravity DB from commandline: 
`sudo sqlite3 /etc/pihole/gravity.db "INSERT INTO adlist (address, enabled, comment) VALUES ('https://domain.com/blocklist.txt', 1, 'comment')"`

Then update gravity
`pihole updateGravity`

There should be a list of blocklists as URL's defined as part of cloud deployment scripts so any rebuild from the ground up already adds to chosed blocklists.

https://docs.pi-hole.net/core/pihole-command/#gravity

**Comment by jsamuel1** [comment]
Committed a change to create an initial set of blocklists based on above.
